#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WikipediaTable {
    Actor,
    Archive,
    Block,
    BlockTarget,
    BotPasswords,
    Category,
    CategoryLinks,
    ChangeTag,
    ChangeTagDef,
    Collation,
    Comment,
    Content,
    ContentModels,
    ExistenceLinks,
    ExternalLinks,
    File,
    FileArchive,
    FileRevision,
    FileTypes,
    Image,
    ImageLinks,
    Interwiki,
    IpChanges,
    IpblocksRestrictions,
    IwLinks,
    Job,
    L10nCache,
    LangLinks,
    LinkTarget,
    LogSearch,
    Logging,
    ObjectCache,
    OldImage,
    Page,
    PageProps,
    PageRestrictions,
    PageLinks,
    ProtectedTitles,
    QueryCache,
    QueryCacheInfo,
    QueryCacheTwo,
    RecentChanges,
    Redirect,
    Revision,
    SearchIndex,
    SiteIdentifiers,
    SiteStats,
    Sites,
    SlotRoles,
    Slots,
    TemplateLinks,
    Text,
    UpdateLog,
    UploadStash,
    User,
    UserAutocreateSerial,
    UserFormerGroups,
    UserGroups,
    UserNewTalk,
    UserProperties,
    Watchlist,
    WatchlistExpiry,
    WatchlistLabel,
    WatchlistLabelMember,
}

pub const ALL_TABLES: [WikipediaTable; 64] = [
    WikipediaTable::Actor,
    WikipediaTable::Archive,
    WikipediaTable::Block,
    WikipediaTable::BlockTarget,
    WikipediaTable::BotPasswords,
    WikipediaTable::Category,
    WikipediaTable::CategoryLinks,
    WikipediaTable::ChangeTag,
    WikipediaTable::ChangeTagDef,
    WikipediaTable::Collation,
    WikipediaTable::Comment,
    WikipediaTable::Content,
    WikipediaTable::ContentModels,
    WikipediaTable::ExistenceLinks,
    WikipediaTable::ExternalLinks,
    WikipediaTable::File,
    WikipediaTable::FileArchive,
    WikipediaTable::FileRevision,
    WikipediaTable::FileTypes,
    WikipediaTable::Image,
    WikipediaTable::ImageLinks,
    WikipediaTable::Interwiki,
    WikipediaTable::IpChanges,
    WikipediaTable::IpblocksRestrictions,
    WikipediaTable::IwLinks,
    WikipediaTable::Job,
    WikipediaTable::L10nCache,
    WikipediaTable::LangLinks,
    WikipediaTable::LinkTarget,
    WikipediaTable::LogSearch,
    WikipediaTable::Logging,
    WikipediaTable::ObjectCache,
    WikipediaTable::OldImage,
    WikipediaTable::Page,
    WikipediaTable::PageProps,
    WikipediaTable::PageRestrictions,
    WikipediaTable::PageLinks,
    WikipediaTable::ProtectedTitles,
    WikipediaTable::QueryCache,
    WikipediaTable::QueryCacheInfo,
    WikipediaTable::QueryCacheTwo,
    WikipediaTable::RecentChanges,
    WikipediaTable::Redirect,
    WikipediaTable::Revision,
    WikipediaTable::SearchIndex,
    WikipediaTable::SiteIdentifiers,
    WikipediaTable::SiteStats,
    WikipediaTable::Sites,
    WikipediaTable::SlotRoles,
    WikipediaTable::Slots,
    WikipediaTable::TemplateLinks,
    WikipediaTable::Text,
    WikipediaTable::UpdateLog,
    WikipediaTable::UploadStash,
    WikipediaTable::User,
    WikipediaTable::UserAutocreateSerial,
    WikipediaTable::UserFormerGroups,
    WikipediaTable::UserGroups,
    WikipediaTable::UserNewTalk,
    WikipediaTable::UserProperties,
    WikipediaTable::Watchlist,
    WikipediaTable::WatchlistExpiry,
    WikipediaTable::WatchlistLabel,
    WikipediaTable::WatchlistLabelMember,
];

impl WikipediaTable {
    pub fn table_name(self) -> &'static str {
        match self {
            Self::Actor => "actor",
            Self::Archive => "archive",
            Self::Block => "block",
            Self::BlockTarget => "block_target",
            Self::BotPasswords => "bot_passwords",
            Self::Category => "category",
            Self::CategoryLinks => "categorylinks",
            Self::ChangeTag => "change_tag",
            Self::ChangeTagDef => "change_tag_def",
            Self::Collation => "collation",
            Self::Comment => "comment",
            Self::Content => "content",
            Self::ContentModels => "content_models",
            Self::ExistenceLinks => "existencelinks",
            Self::ExternalLinks => "externallinks",
            Self::File => "file",
            Self::FileArchive => "filearchive",
            Self::FileRevision => "filerevision",
            Self::FileTypes => "filetypes",
            Self::Image => "image",
            Self::ImageLinks => "imagelinks",
            Self::Interwiki => "interwiki",
            Self::IpChanges => "ip_changes",
            Self::IpblocksRestrictions => "ipblocks_restrictions",
            Self::IwLinks => "iwlinks",
            Self::Job => "job",
            Self::L10nCache => "l10n_cache",
            Self::LangLinks => "langlinks",
            Self::LinkTarget => "linktarget",
            Self::LogSearch => "log_search",
            Self::Logging => "logging",
            Self::ObjectCache => "objectcache",
            Self::OldImage => "oldimage",
            Self::Page => "page",
            Self::PageProps => "page_props",
            Self::PageRestrictions => "page_restrictions",
            Self::PageLinks => "pagelinks",
            Self::ProtectedTitles => "protected_titles",
            Self::QueryCache => "querycache",
            Self::QueryCacheInfo => "querycache_info",
            Self::QueryCacheTwo => "querycachetwo",
            Self::RecentChanges => "recentchanges",
            Self::Redirect => "redirect",
            Self::Revision => "revision",
            Self::SearchIndex => "searchindex",
            Self::SiteIdentifiers => "site_identifiers",
            Self::SiteStats => "site_stats",
            Self::Sites => "sites",
            Self::SlotRoles => "slot_roles",
            Self::Slots => "slots",
            Self::TemplateLinks => "templatelinks",
            Self::Text => "text",
            Self::UpdateLog => "updatelog",
            Self::UploadStash => "uploadstash",
            Self::User => "user",
            Self::UserAutocreateSerial => "user_autocreate_serial",
            Self::UserFormerGroups => "user_former_groups",
            Self::UserGroups => "user_groups",
            Self::UserNewTalk => "user_newtalk",
            Self::UserProperties => "user_properties",
            Self::Watchlist => "watchlist",
            Self::WatchlistExpiry => "watchlist_expiry",
            Self::WatchlistLabel => "watchlist_label",
            Self::WatchlistLabelMember => "watchlist_label_member",
        }
    }

    pub fn column_names(self) -> &'static [&'static str] {
        match self {
            Self::Actor => &["actor_id", "actor_user", "actor_name"],
            Self::Archive => &[
                "ar_id",
                "ar_namespace",
                "ar_title",
                "ar_comment_id",
                "ar_actor",
                "ar_timestamp",
                "ar_minor_edit",
                "ar_rev_id",
                "ar_deleted",
                "ar_len",
                "ar_page_id",
                "ar_parent_id",
            ],
            Self::Block => &[
                "bl_id",
                "bl_target",
                "bl_by_actor",
                "bl_reason_id",
                "bl_timestamp",
                "bl_anon_only",
                "bl_create_account",
                "bl_enable_autoblock",
                "bl_expiry",
                "bl_deleted",
                "bl_block_email",
                "bl_allow_usertalk",
                "bl_parent_block_id",
                "bl_sitewide",
            ],
            Self::BlockTarget => &[
                "bt_id",
                "bt_address",
                "bt_user",
                "bt_user_text",
                "bt_auto",
                "bt_range_start",
                "bt_range_end",
                "bt_ip_hex",
                "bt_count",
            ],
            Self::BotPasswords => &[
                "bp_user",
                "bp_app_id",
                "bp_password",
                "bp_token",
                "bp_restrictions",
                "bp_grants",
            ],
            Self::Category => &[
                "cat_id",
                "cat_title",
                "cat_pages",
                "cat_subcats",
                "cat_files",
            ],
            Self::CategoryLinks => &[
                "cl_from",
                "cl_target_id",
                "cl_sortkey",
                "cl_sortkey_prefix",
                "cl_timestamp",
                "cl_type",
                "cl_collation_id",
            ],
            Self::ChangeTag => &[
                "ct_id",
                "ct_rc_id",
                "ct_log_id",
                "ct_rev_id",
                "ct_params",
                "ct_tag_id",
            ],
            Self::ChangeTagDef => &["ctd_id", "ctd_name", "ctd_user_defined", "ctd_count"],
            Self::Collation => &["collation_id", "collation_name"],
            Self::Comment => &["comment_id", "comment_hash", "comment_text", "comment_data"],
            Self::Content => &[
                "content_id",
                "content_size",
                "content_sha1",
                "content_model",
                "content_address",
            ],
            Self::ContentModels => &["model_id", "model_name"],
            Self::ExistenceLinks => &["exl_from", "exl_target_id"],
            Self::ExternalLinks => &["el_id", "el_from", "el_to_domain_index", "el_to_path"],
            Self::File => &[
                "file_id",
                "file_name",
                "file_latest",
                "file_type",
                "file_deleted",
            ],
            Self::FileArchive => &[
                "fa_id",
                "fa_name",
                "fa_archive_name",
                "fa_storage_group",
                "fa_storage_key",
                "fa_deleted_user",
                "fa_deleted_timestamp",
                "fa_deleted_reason_id",
                "fa_size",
                "fa_width",
                "fa_height",
                "fa_metadata",
                "fa_bits",
                "fa_media_type",
                "fa_major_mime",
                "fa_minor_mime",
                "fa_description_id",
                "fa_actor",
                "fa_timestamp",
                "fa_deleted",
                "fa_sha1",
            ],
            Self::FileRevision => &[
                "fr_id",
                "fr_file",
                "fr_size",
                "fr_width",
                "fr_height",
                "fr_metadata",
                "fr_bits",
                "fr_description_id",
                "fr_actor",
                "fr_timestamp",
                "fr_sha1",
                "fr_archive_name",
                "fr_deleted",
            ],
            Self::FileTypes => &["ft_id", "ft_media_type", "ft_major_mime", "ft_minor_mime"],
            Self::Image => &[
                "img_name",
                "img_size",
                "img_width",
                "img_height",
                "img_metadata",
                "img_bits",
                "img_media_type",
                "img_major_mime",
                "img_minor_mime",
                "img_description_id",
                "img_actor",
                "img_timestamp",
                "img_sha1",
            ],
            Self::ImageLinks => &["il_from", "il_target_id", "il_from_namespace", "il_to"],
            Self::Interwiki => &[
                "iw_prefix",
                "iw_url",
                "iw_api",
                "iw_wikiid",
                "iw_local",
                "iw_trans",
            ],
            Self::IpChanges => &["ipc_rev_id", "ipc_rev_timestamp", "ipc_hex"],
            Self::IpblocksRestrictions => &["ir_ipb_id", "ir_type", "ir_value"],
            Self::IwLinks => &["iwl_from", "iwl_prefix", "iwl_title"],
            Self::Job => &[
                "job_id",
                "job_cmd",
                "job_namespace",
                "job_title",
                "job_timestamp",
                "job_params",
                "job_random",
                "job_attempts",
                "job_token",
                "job_token_timestamp",
                "job_sha1",
            ],
            Self::L10nCache => &["lc_lang", "lc_key", "lc_value"],
            Self::LangLinks => &["ll_from", "ll_lang", "ll_title"],
            Self::LinkTarget => &["lt_id", "lt_namespace", "lt_title"],
            Self::LogSearch => &["ls_field", "ls_value", "ls_log_id"],
            Self::Logging => &[
                "log_id",
                "log_type",
                "log_action",
                "log_timestamp",
                "log_actor",
                "log_namespace",
                "log_title",
                "log_page",
                "log_comment_id",
                "log_params",
                "log_deleted",
            ],
            Self::ObjectCache => &["keyname", "value", "exptime"],
            Self::OldImage => &[
                "oi_name",
                "oi_archive_name",
                "oi_size",
                "oi_width",
                "oi_height",
                "oi_bits",
                "oi_description_id",
                "oi_actor",
                "oi_timestamp",
                "oi_metadata",
                "oi_media_type",
                "oi_major_mime",
                "oi_minor_mime",
                "oi_deleted",
                "oi_sha1",
            ],
            Self::Page => &[
                "page_id",
                "page_namespace",
                "page_title",
                "page_is_redirect",
                "page_is_new",
                "page_random",
                "page_touched",
                "page_links_updated",
                "page_latest",
                "page_len",
                "page_content_model",
                "page_lang",
            ],
            Self::PageProps => &["pp_page", "pp_propname", "pp_value", "pp_sortkey"],
            Self::PageRestrictions => &[
                "pr_id",
                "pr_page",
                "pr_type",
                "pr_level",
                "pr_cascade",
                "pr_expiry",
            ],
            Self::PageLinks => &["pl_from", "pl_target_id", "pl_from_namespace"],
            Self::ProtectedTitles => &[
                "pt_namespace",
                "pt_title",
                "pt_user",
                "pt_reason_id",
                "pt_timestamp",
                "pt_expiry",
                "pt_create_perm",
            ],
            Self::QueryCache => &["qc_type", "qc_value", "qc_namespace", "qc_title"],
            Self::QueryCacheInfo => &["qci_type", "qci_timestamp"],
            Self::QueryCacheTwo => &[
                "qcc_type",
                "qcc_value",
                "qcc_namespace",
                "qcc_title",
                "qcc_namespacetwo",
                "qcc_titletwo",
            ],
            Self::RecentChanges => &[
                "rc_id",
                "rc_timestamp",
                "rc_actor",
                "rc_namespace",
                "rc_title",
                "rc_comment_id",
                "rc_minor",
                "rc_bot",
                "rc_cur_id",
                "rc_this_oldid",
                "rc_last_oldid",
                "rc_source",
                "rc_patrolled",
                "rc_ip",
                "rc_old_len",
                "rc_new_len",
                "rc_deleted",
                "rc_logid",
                "rc_log_type",
                "rc_log_action",
                "rc_params",
            ],
            Self::Redirect => &[
                "rd_from",
                "rd_namespace",
                "rd_title",
                "rd_interwiki",
                "rd_fragment",
            ],
            Self::Revision => &[
                "rev_id",
                "rev_page",
                "rev_comment_id",
                "rev_actor",
                "rev_timestamp",
                "rev_minor_edit",
                "rev_deleted",
                "rev_len",
                "rev_parent_id",
            ],
            Self::SearchIndex => &["si_page", "si_title", "si_text"],
            Self::SiteIdentifiers => &["si_type", "si_key", "si_site"],
            Self::SiteStats => &[
                "ss_row_id",
                "ss_total_edits",
                "ss_good_articles",
                "ss_total_pages",
                "ss_users",
                "ss_active_users",
                "ss_images",
            ],
            Self::Sites => &[
                "site_id",
                "site_global_key",
                "site_type",
                "site_group",
                "site_source",
                "site_language",
                "site_protocol",
                "site_domain",
                "site_data",
                "site_forward",
                "site_config",
            ],
            Self::SlotRoles => &["role_id", "role_name"],
            Self::Slots => &[
                "slot_revision_id",
                "slot_role_id",
                "slot_content_id",
                "slot_origin",
            ],
            Self::TemplateLinks => &["tl_from", "tl_target_id", "tl_from_namespace"],
            Self::Text => &["old_id", "old_text", "old_flags"],
            Self::UpdateLog => &["ul_key", "ul_value"],
            Self::UploadStash => &[
                "us_id",
                "us_user",
                "us_key",
                "us_orig_path",
                "us_path",
                "us_source_type",
                "us_timestamp",
                "us_status",
                "us_chunk_inx",
                "us_props",
                "us_size",
                "us_sha1",
                "us_mime",
                "us_media_type",
                "us_image_width",
                "us_image_height",
                "us_image_bits",
            ],
            Self::User => &[
                "user_id",
                "user_name",
                "user_real_name",
                "user_password",
                "user_newpassword",
                "user_newpass_time",
                "user_email",
                "user_touched",
                "user_token",
                "user_email_authenticated",
                "user_email_token",
                "user_email_token_expires",
                "user_registration",
                "user_editcount",
                "user_password_expires",
                "user_is_temp",
            ],
            Self::UserAutocreateSerial => &["uas_shard", "uas_year", "uas_value"],
            Self::UserFormerGroups => &["ufg_user", "ufg_group"],
            Self::UserGroups => &["ug_user", "ug_group", "ug_expiry"],
            Self::UserNewTalk => &["user_id", "user_ip", "user_last_timestamp"],
            Self::UserProperties => &["up_user", "up_property", "up_value"],
            Self::Watchlist => &[
                "wl_id",
                "wl_user",
                "wl_namespace",
                "wl_title",
                "wl_notificationtimestamp",
            ],
            Self::WatchlistExpiry => &["we_item", "we_expiry"],
            Self::WatchlistLabel => &["wll_id", "wll_user", "wll_name"],
            Self::WatchlistLabelMember => &["wlm_label", "wlm_item"],
        }
    }

    pub fn expected_columns(self) -> usize {
        self.column_names().len()
    }

    pub fn from_table_name(name: &str) -> Option<Self> {
        match name {
            "actor" => Some(Self::Actor),
            "archive" => Some(Self::Archive),
            "block" => Some(Self::Block),
            "block_target" => Some(Self::BlockTarget),
            "bot_passwords" => Some(Self::BotPasswords),
            "category" => Some(Self::Category),
            "categorylinks" => Some(Self::CategoryLinks),
            "change_tag" => Some(Self::ChangeTag),
            "change_tag_def" => Some(Self::ChangeTagDef),
            "collation" => Some(Self::Collation),
            "comment" => Some(Self::Comment),
            "content" => Some(Self::Content),
            "content_models" => Some(Self::ContentModels),
            "existencelinks" => Some(Self::ExistenceLinks),
            "externallinks" => Some(Self::ExternalLinks),
            "file" => Some(Self::File),
            "filearchive" => Some(Self::FileArchive),
            "filerevision" => Some(Self::FileRevision),
            "filetypes" => Some(Self::FileTypes),
            "image" => Some(Self::Image),
            "imagelinks" => Some(Self::ImageLinks),
            "interwiki" => Some(Self::Interwiki),
            "ip_changes" => Some(Self::IpChanges),
            "ipblocks_restrictions" => Some(Self::IpblocksRestrictions),
            "iwlinks" => Some(Self::IwLinks),
            "job" => Some(Self::Job),
            "l10n_cache" => Some(Self::L10nCache),
            "langlinks" => Some(Self::LangLinks),
            "linktarget" => Some(Self::LinkTarget),
            "log_search" => Some(Self::LogSearch),
            "logging" => Some(Self::Logging),
            "objectcache" => Some(Self::ObjectCache),
            "oldimage" => Some(Self::OldImage),
            "page" => Some(Self::Page),
            "page_props" => Some(Self::PageProps),
            "page_restrictions" => Some(Self::PageRestrictions),
            "pagelinks" => Some(Self::PageLinks),
            "protected_titles" => Some(Self::ProtectedTitles),
            "querycache" => Some(Self::QueryCache),
            "querycache_info" => Some(Self::QueryCacheInfo),
            "querycachetwo" => Some(Self::QueryCacheTwo),
            "recentchanges" => Some(Self::RecentChanges),
            "redirect" => Some(Self::Redirect),
            "revision" => Some(Self::Revision),
            "searchindex" => Some(Self::SearchIndex),
            "site_identifiers" => Some(Self::SiteIdentifiers),
            "site_stats" => Some(Self::SiteStats),
            "sites" => Some(Self::Sites),
            "slot_roles" => Some(Self::SlotRoles),
            "slots" => Some(Self::Slots),
            "templatelinks" => Some(Self::TemplateLinks),
            "text" => Some(Self::Text),
            "updatelog" => Some(Self::UpdateLog),
            "uploadstash" => Some(Self::UploadStash),
            "user" => Some(Self::User),
            "user_autocreate_serial" => Some(Self::UserAutocreateSerial),
            "user_former_groups" => Some(Self::UserFormerGroups),
            "user_groups" => Some(Self::UserGroups),
            "user_newtalk" => Some(Self::UserNewTalk),
            "user_properties" => Some(Self::UserProperties),
            "watchlist" => Some(Self::Watchlist),
            "watchlist_expiry" => Some(Self::WatchlistExpiry),
            "watchlist_label" => Some(Self::WatchlistLabel),
            "watchlist_label_member" => Some(Self::WatchlistLabelMember),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{ALL_TABLES, WikipediaTable};

    #[test]
    fn roundtrip_table_name_for_all_tables() {
        for table in ALL_TABLES {
            assert_eq!(
                WikipediaTable::from_table_name(table.table_name()),
                Some(table)
            );
        }
    }

    #[test]
    fn expected_columns_matches_column_name_count() {
        for table in ALL_TABLES {
            assert_eq!(table.expected_columns(), table.column_names().len());
        }
    }
}
